#!/bin/sh
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N rcor_dryo_array
#$ -q omni
#$ -pe sm 4
#$ -P quanah
#$ -t 7-12
#$ -l h_rt=48:00:00
#$ -l h_vmem=12G

perl /home/sabaty/rcorrector/rcorrector/run_rcorrector.pl \
-1 /lustre/scratch/sabaty/woodpecker-project/dryobates_transcriptomes/${SGE_TASK_ID}_R1.fastq.gz \
-2 /lustre/scratch/sabaty/woodpecker-project/dryobates_transcriptomes/${SGE_TASK_ID}_R2.fastq.gz \
-t 4 \
-od /lustre/scratch/sabaty/woodpecker-project/dryobates_transcriptomes/d-rcor-results
