#!/bin/sh
#$ -V
#$ -cwd
#$ -S /bin/bash
#$ -N sam_dryo
#$ -q omni
#$ -pe sm 4
#$ -P quanah
#$ -t 7-12
#$ -l h_rt=48:00:00
#$ -l h_vmem=12G

samtools sort -m 12G -o /lustre/scratch/sabaty/woodpecker-project/samtools/dryobates_sort/${SGE_TASK_ID}_dryobates.sam -O SAM -n /lustre/scratch/sabaty/woodpecker-project/hisat/dryobates_align_2/${SGE_TASK_ID}_dryo_picoides_align.sam
